### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by dhdiu** [Gainss/Action_Kernel#2]
fork大佬的项目编译失败
自己写了一个新项目也还是无法运行
希望大佬可以帮我修改错误

**Comment by Gainss** [comment]
请问我如何联系你呢，可以留下你的联系方式吗？

**Comment by Gainss** [comment]
> fork大佬的项目编译失败 自己写了一个新项目也还是无法运行 希望大佬可以帮我修改错误
请问我怎么联系你呢，可以留下你的联系方式交流吗

**Comment by Gainss** [comment]
> fork大佬的项目编译失败 自己写了一个新项目也还是无法运行 希望大佬可以帮我修改错误

请问我怎么联系你呢，可以留下你的联系方式交流吗

**Comment by dhdiu** [comment]
谢谢
